stages:
  - build
  - test
  - docker
  - deploy

# variables:
  # IMAGE_NAME: $DOCKER_USERNAME/linkin
  # APP_VERSION: $CI_PIPELINE_IID

smoke-test:
  stage: test
  image: docker:24

  before_script:
    - apk add --no-cache curl
    - env | grep -E '^(PORT|MONGO_URI|JWT_SECRET|JWT_EXPIRES_IN)' >> .env
  services:
    - docker:dind

  script:
    - docker build -t linkin .
    - cat .env
    - docker run -d --name linkin -p 5000:5000 --env-file .env linkin
    - sleep 10
    - docker network ls
    - docker logs linkin
    - curl -s http://linkin:5000 
.docker-build:
  stage: docker
  image: docker:24

  services:
    - docker:dind

  script:
    - echo "username:" $DOCKER_USERNAME "password:" $DOCKER_PASSWORD     
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $IMAGE_NAME:$APP_VERSION .
    - docker push $IMAGE_NAME:$APP_VERSION


.deploy:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client

    - mkdir -p ~/.ssh

    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

    - chmod 600 ~/.ssh/id_rsa

  script:
    - |
      ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "


      "
